sudo: false
language: python
python:
  - "3.6"

dist: trusty

addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
    - libc6:i386
    - ocl-icd-libopencl1

before_install:
 # install Futhark
 - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
 - tar xf futhark-nightly-linux-x86_64.tar.xz
 - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)
 - pip install -r requirements.txt

install:
  - ./setup.sh

script:
  - python test.py
